import * as FileSystem from 'expo-file-system';
import * as Sharing from 'expo-sharing';
import * as Print from 'expo-print';
import { utils, write } from 'xlsx';
import { RegisterDetail, Entry } from './api';

/**
 * Service for exporting register data to various formats (CSV, Excel, PDF)
 */

export const ExportService = {
  /**
   * Export register to CSV and share
   */
  async exportToCSV(register: RegisterDetail, entries: Entry[]) {
    try {
      const cols = register.columns;
      const headers = ['S.No.', ...cols.map((c) => c.name)];
      const headerRow = headers.map((h) => `"${h.replace(/"/g, '""')}"`).join(',');
      
      const dataRows = entries.map((entry, idx) => {
        const row = [
          (idx + 1).toString(),
          ...cols.map((col) => {
            const val = entry.cells?.[col.id.toString()] || '';
            return `"${val.toString().replace(/"/g, '""')}"`;
          })
        ];
        return row.join(',');
      });
      
      const csvContent = [headerRow, ...dataRows].join('\n');
      const filename = `${register.name.replace(/\s+/g, '_')}_${new Date().getTime()}.csv`;
      const fileUri = `${FileSystem.cacheDirectory}${filename}`;
      
      await FileSystem.writeAsStringAsync(fileUri, csvContent, { encoding: FileSystem.EncodingType.UTF8 });
      await Sharing.shareAsync(fileUri, { mimeType: 'text/csv', dialogTitle: 'Export CSV', UTI: 'public.comma-separated-values-text' });
    } catch (error) {
      console.error('Export CSV Error:', error);
      throw error;
    }
  },

  /**
   * Export register to Excel (XLSX) and share
   */
  async exportToExcel(register: RegisterDetail, entries: Entry[]) {
    try {
      const cols = register.columns;
      const data = entries.map((entry, idx) => {
        const row: any = { 'S.No.': idx + 1 };
        cols.forEach((col) => {
          row[col.name] = entry.cells?.[col.id.toString()] || '';
        });
        return row;
      });

      const ws = utils.json_to_sheet(data);
      const wb = utils.book_new();
      utils.book_append_sheet(wb, ws, 'Register Data');
      
      const wbout = write(wb, { type: 'base64', bookType: 'xlsx' });
      const filename = `${register.name.replace(/\s+/g, '_')}_${new Date().getTime()}.xlsx`;
      const fileUri = `${FileSystem.cacheDirectory}${filename}`;
      
      await FileSystem.writeAsStringAsync(fileUri, wbout, { encoding: FileSystem.EncodingType.Base64 });
      await Sharing.shareAsync(fileUri, { mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', dialogTitle: 'Export Excel', UTI: 'com.microsoft.excel.xlsx' });
    } catch (error) {
      console.error('Export Excel Error:', error);
      throw error;
    }
  },

  /**
   * Export register to PDF and share
   */
  async exportToPDF(register: RegisterDetail, entries: Entry[]) {
    try {
      const cols = register.columns;
      
      let tableHtml = `
        <html>
          <head>
            <style>
              body { font-family: 'Helvetica', sans-serif; padding: 20px; }
              h1 { color: #1a237e; text-align: center; margin-bottom: 5px; }
              p { text-align: center; color: #666; margin-bottom: 20px; }
              table { width: 100%; border-collapse: collapse; margin-top: 20px; }
              th { background-color: #1a237e; color: white; padding: 10px; text-align: left; font-size: 12px; }
              td { border: 1px solid #ddd; padding: 8px; font-size: 11px; }
              tr:nth-child(even) { background-color: #f2f2f2; }
              .footer { margin-top: 30px; text-align: center; font-size: 10px; color: #999; }
            </style>
          </head>
          <body>
            <h1>${register.name}</h1>
            <p>Exported on ${new Date().toLocaleDateString()} at ${new Date().toLocaleDateString()}</p>
            <table>
              <thead>
                <tr>
                  <th>S.No.</th>
                  ${cols.map(c => `<th>${c.name}</th>`).join('')}
                </tr>
              </thead>
              <tbody>
                ${entries.map((entry, idx) => `
                  <tr>
                    <td>${idx + 1}</td>
                    ${cols.map(col => `<td>${entry.cells?.[col.id.toString()] || ''}</td>`).join('')}
                  </tr>
                `).join('')}
              </tbody>
            </table>
            <div class="footer">Generated by SJVPS Record Book</div>
          </body>
        </html>
      `;

      const { uri } = await Print.printToFileAsync({ html: tableHtml });
      const filename = `${register.name.replace(/\s+/g, '_')}_${new Date().getTime()}.pdf`;
      const newUri = `${FileSystem.cacheDirectory}${filename}`;
      
      await FileSystem.moveAsync({ from: uri, to: newUri });
      await Sharing.shareAsync(newUri, { mimeType: 'application/pdf', dialogTitle: 'Export PDF', UTI: 'com.adobe.pdf' });
    } catch (error) {
      console.error('Export PDF Error:', error);
      throw error;
    }
  }
};
